#!/bin/bash

set -e

echo "POSTGRES_USER_FILE = 'postgres'"
echo "ALT_PASSWORD_FILE = '$ALT_PASSWORD_FILE'"
echo "POSTGRES_T_U_FILE = '$POSTGRES_T_U_FILE'"
echo "POSTGRES_T_P_FILE = '$POSTGRES_T_P_FILE'"
echo "POSTGRES_DB_T_FILE = '$POSTGRES_DB_T_FILE'"
echo "REPLICATOR_USER_FILE = '$REPLICATOR_USER_FILE'"
echo "REPLICATOR_PASSWORD_FILE = 'ReplicatorPass123'"
echo "REPLICATOR_PASSWORD_FILE = '$REPLICA_PASSWORD_FILE'"
echo "BARMAN_USER = '$BARMAN_USER'"
echo "BARMAN_PASSWORD_FILE = '$BARMAN_PASSWORD_FILE'"

#POSTGRES_USER=$(cat "$POSTGRES_USER_FILE")
ALT_PASSWORD=$(cat "$ALT_PASSWORD_FILE")
POSTGRES_T_U=$(cat "$POSTGRES_T_U_FILE")
POSTGRES_T_P=$(cat "$POSTGRES_T_P_FILE")
POSTGRES_DB_T=$(cat "$POSTGRES_DB_T_FILE")

REPLICATOR_USER="replicator"
REPLICATOR_PASSWORD="ReplicatorPass123"
BARMAN_USER=$(cat "$BARMAN_USER_FILE")
BARMAN_PASSWORD=$(cat "$BARMAN_PASSWORD_FILE")
REPLICA_PASSWORD=$(cat "$REPLICA_PASSWORD_FILE")


cp /tmp/pg_hba.conf /var/lib/postgresql/data/pg_hba.conf
cp /tmp/postgresql.conf /var/lib/postgresql/data/postgresql.conf
mkdir /var/lib/postgresql/wal_archive

psql -v ON_ERROR_STOP=1 --username "postgres" <<-EOSQL
    ALTER USER postgres WITH PASSWORD '$ALT_PASSWORD';
    CREATE DATABASE $POSTGRES_DB_T;
    CREATE USER $POSTGRES_T_U WITH PASSWORD '$POSTGRES_T_P';
    GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_DB_T TO $POSTGRES_T_U;
    CREATE ROLE $REPLICATOR_USER WITH REPLICATION LOGIN PASSWORD '$REPLICATOR_PASSWORD';
    CREATE ROLE $BARMAN_USER WITH PASSWORD '$BARMAN_PASSWORD';
EOSQL

